### ISSUE TITLE
Cabal 2.0 compatibility

### ISSUE THREAD

**Issue by turboMaCk** [zwilias/elm-instrument#2]
There is a breaking change in newer versions of cabal which will affect build of this package in future versions of Cabal and GHC. Namely it's a deprecation of `autogenModulesDir` function used in `Setup.hs`. See [upgrade guide](https://github.com/haskell/cabal/wiki/2.0-migration-guide#cabal_macrosh) for details

**Comment by zwilias** [comment]
Cool, thanks for the PR!
